doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: false
    mappings:
      Api:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/src/Videolibrary/Api/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: 'Videolibrary\Api\Infrastructure\Persistence\Doctrine\Entity'
        alias: Api

#      App:
#        is_bundle: false
#        type: attribute
#        dir: '%kernel.project_dir%/src/Entity'
#        prefix: 'App\Entity'
#        alias: App
