Videolibrary\Api\Infrastructure\Persistence\Doctrine\Entity\Subtitle:
  type: entity
  table: subtitle
  indexes:
    IDX_518597B129C1004E:
      columns:
        - video_id
  id:
    id:
      type: uuid
  fields:
    language:
      type: string
      nullable: false
      length: 2
  manyToOne:
    video:
      targetEntity: Videolibrary\Api\Infrastructure\Persistence\Doctrine\Entity\Video
  lifecycleCallbacks: { }
